- ros_topic_name: "/clock"
  ign_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  ign_type_name: "ign.msgs.Clock"
  direction: IGN_TO_ROS

- ros_topic_name: "/scan"
  ign_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  ign_type_name: "ign.msgs.LaserScan"
  direction: IGN_TO_ROS 
  
- ros_topic_name: "/tf"
  ign_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  ign_type_name: "ign.msgs.Pose_V"
  direction: IGN_TO_ROS   

- ros_topic_name: "/joint_states"
  ign_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  ign_type_name: "ign.msgs.Model"
  direction: IGN_TO_ROS   

- ros_topic_name: "/cmd_vel"
  ign_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  ign_type_name: "ign.msgs.Twist"
  direction: ROS_TO_IGN   

- ros_topic_name: "/scan/points"
  ign_topic_name: "/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  ign_type_name: "ign.msgs.PointCloudPacked"
  direction: IGN_TO_ROS

- ros_topic_name: "/depth_camera/camera_info"
  ign_topic_name: "/depth_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  ign_type_name: "ign.msgs.CameraInfo"
  direction: IGN_TO_ROS

- ros_topic_name: "/depth_camera/points"
  ign_topic_name: "/depth_camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  ign_type_name: "ign.msgs.PointCloudPacked"
  direction: IGN_TO_ROS

- ros_topic_name: "/depth_camera/image_raw"
  ign_topic_name: "/depth_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  ign_type_name: "ign.msgs.Image"
  direction: IGN_TO_ROS
